### ISSUE TITLE
SHTOOLS Installation

### ISSUE THREAD

**Issue by Mstabdelbaky** [pletnes/SHTOOLS#1]
I would to use SHTOOLS programs. when i installed the SHTOOLS, i got this error and i don't know the reasons. I wish if you can help me to solve this error.
Thank you.
![shtools p1](https://cloud.githubusercontent.com/assets/16101683/11502973/b64d1b3e-9846-11e5-845b-40976cc97472.png)

Best Regards,
Mostafa

**Comment by pletnes** [comment]
Hi, I somehow discovered this today. I do hope you solved your issue. Closing as it's 5 years old.
